name: Discord Bot CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Tesseract dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            tesseract-ocr \
            libtesseract5 \
            liblept5 \
            libgif7 \
            libjpeg8 \
            libpng16-16 \
            libtiff6 \
            libwebp7 \
            libopenjp2-7 \
            zlib1g \
            libarchive13 \
            libcurl4

      - name: Cache Tesseract dependencies
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/tesseract
          key: ${{ runner.os }}-tesseract-v1

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  bot:
    needs: setup
    runs-on: ubuntu-latest
    concurrency:
      group: discord-bot
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set environment variables for Tesseract
        run: |
          echo "PATH=$PATH:/usr/local/bin" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata" >> $GITHUB_ENV

      - name: Verify Tesseract installation
        run: |
          tesseract --version

      - name: Run Discord bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          . .venv/bin/activate
          python bot.py
