name: Discord Bot CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download Tesseract packages
        run: |
          sudo apt-get update -y
          apt download tesseract-ocr libtesseract4 liblept5 tesseract-ocr-eng

      - name: Extract packages
        run: |
          mkdir tesseract-local
          for deb in *.deb; do
            dpkg-deb -x $deb tesseract-local
          done

      - name: Cache Tesseract local installation
        uses: actions/cache@v3
        with:
          path: tesseract-local
          key: ${{ runner.os }}-tesseract-v1

      - name: Cache virtual environment
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

      - name: Set up virtual environment if cache miss
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

  bot:
    needs: setup
    runs-on: ubuntu-latest
    concurrency:
      group: discord-bot
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Restore Tesseract cache
        uses: actions/cache/restore@v3
        with:
          path: tesseract-local
          key: ${{ runner.os }}-tesseract-v1

      - name: Restore virtual environment cache
        uses: actions/cache/restore@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

      - name: Set environment variables for Tesseract
        run: |
          echo "PATH=$PATH:$GITHUB_WORKSPACE/tesseract-local/usr/bin" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/tesseract-local/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          TESSDATA_DIR=$(find $GITHUB_WORKSPACE/tesseract-local -type d -name tessdata)
          echo "TESSDATA_PREFIX=$TESSDATA_DIR" >> $GITHUB_ENV

      - name: Verify Tesseract
        run: tesseract --version

      - name: Run Discord bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          . .venv/bin/activate
          python bot.py
