name: Discord Bot CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Tesseract
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends tesseract-ocr tesseract-ocr-eng
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      
      - name: Save repo and dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            .
            ~/.cache/pip
          key: ${{ github.sha }}-${{ github.run_id }}

  bot:
    needs: setup
    runs-on: ubuntu-latest
    concurrency:
      group: discord-bot
      cancel-in-progress: true
    steps:
      - name: Restore repo and dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            .
            ~/.cache/pip
          key: ${{ github.sha }}-${{ github.run_id }}
          fail-on-cache-miss: true
      
      - name: Run Discord bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python bot.py
